class AddCountriesRegions < ActiveRecord::Migration
  def up
  # Typ_Country
  TypCountry.create(id: 1, country: '基隆市', postal_code: '^(d{5})$', geonameid:'1668284')
  TypCountry.create(id: 2, country: '台北市', postal_code: '^(d{5})$', geonameid:'1668284')
  TypCountry.create(id: 3, country: '新北市', postal_code: '^(d{5})$', geonameid:'1668284')
  TypCountry.create(id: 4, country: '桃園市', postal_code: '^(d{5})$', geonameid:'1668284')
  TypCountry.create(id: 5, country: '新竹市', postal_code: '^(d{5})$', geonameid:'1668284')
  TypCountry.create(id: 6, country: '新竹縣', postal_code: '^(d{5})$', geonameid:'1668284')
  TypCountry.create(id: 7, country: '苗栗縣', postal_code: '^(d{5})$', geonameid:'1668284')
  TypCountry.create(id: 8, country: '台中市', postal_code: '^(d{5})$', geonameid:'1668284')
  TypCountry.create(id: 9, country: '彰化縣', postal_code: '^(d{5})$', geonameid:'1668284')
  TypCountry.create(id: 10, country: '南投縣', postal_code: '^(d{5})$', geonameid:'1668284')
  TypCountry.create(id: 11, country: '雲林縣', postal_code: '^(d{5})$', geonameid:'1668284')
  TypCountry.create(id: 12, country: '嘉義市', postal_code: '^(d{5})$', geonameid:'1668284')
  TypCountry.create(id: 13, country: '嘉義縣', postal_code: '^(d{5})$', geonameid:'1668284')
  TypCountry.create(id: 14, country: '台南市', postal_code: '^(d{5})$', geonameid:'1668284')
  TypCountry.create(id: 15, country: '高雄市', postal_code: '^(d{5})$', geonameid:'1668284')
  TypCountry.create(id: 16, country: '屏東縣', postal_code: '^(d{5})$', geonameid:'1668284')
  TypCountry.create(id: 17, country: '台東縣', postal_code: '^(d{5})$', geonameid:'1668284')
  TypCountry.create(id: 18, country: '花蓮縣', postal_code: '^(d{5})$', geonameid:'1668284')
  TypCountry.create(id: 19, country: '宜蘭縣', postal_code: '^(d{5})$', geonameid:'1668284')
  TypCountry.create(id: 20, country: '澎湖縣', postal_code: '^(d{5})$', geonameid:'1668284')
  TypCountry.create(id: 21, country: '金門縣', postal_code: '^(d{5})$', geonameid:'1668284')
  TypCountry.create(id: 22, country: '連江縣', postal_code: '^(d{5})$', geonameid:'1668284');
  # Typ_regions
  # Typ_regions 基隆市
  TypRegion.create(id: 1, typ_country_id: 1, name:'仁愛區')
  TypRegion.create(id: 2, typ_country_id: 1, name:'信義區')
  TypRegion.create(id: 3, typ_country_id: 1, name:'中正區')
  TypRegion.create(id: 4, typ_country_id: 1, name:'中山區')
  TypRegion.create(id: 5, typ_country_id: 1, name:'安樂區')
  TypRegion.create(id: 6, typ_country_id: 1, name:'暖暖區')
  TypRegion.create(id: 7, typ_country_id: 1, name:'七堵區')
  # Typ_regions 台北市
  TypRegion.create(id: 8, typ_country_id: 2, name:'中正區')
  TypRegion.create(id: 9, typ_country_id: 2, name:'大同區')
  TypRegion.create(id: 10, typ_country_id: 2, name:'中山區')
  TypRegion.create(id: 11, typ_country_id: 2, name:'松山區')
  TypRegion.create(id: 12, typ_country_id: 2, name:'大安區')
  TypRegion.create(id: 13, typ_country_id: 2, name:'萬華區')
  TypRegion.create(id: 14, typ_country_id: 2, name:'信義區')
  TypRegion.create(id: 15, typ_country_id: 2, name:'士林區')
  TypRegion.create(id: 16, typ_country_id: 2, name:'北投區')
  TypRegion.create(id: 17, typ_country_id: 2, name:'內湖區')
  TypRegion.create(id: 18, typ_country_id: 2, name:'南港區')
  TypRegion.create(id: 19, typ_country_id: 2, name:'文山區')
  # Typ_regions 新北市
  TypRegion.create(id: 20, typ_country_id: 3, name:'萬里區')
  TypRegion.create(id: 21, typ_country_id: 3, name:'金山區')
  TypRegion.create(id: 22, typ_country_id: 3, name:'板橋區')
  TypRegion.create(id: 23, typ_country_id: 3, name:'汐止區')
  TypRegion.create(id: 24, typ_country_id: 3, name:'深坑區')
  TypRegion.create(id: 25, typ_country_id: 3, name:'石碇區')
  TypRegion.create(id: 26, typ_country_id: 3, name:'瑞芳區')
  TypRegion.create(id: 27, typ_country_id: 3, name:'平溪區')
  TypRegion.create(id: 28, typ_country_id: 3, name:'雙溪區')
  TypRegion.create(id: 29, typ_country_id: 3, name:'貢寮區')
  TypRegion.create(id: 30, typ_country_id: 3, name:'新店區')
  TypRegion.create(id: 31, typ_country_id: 3, name:'坪林區')
  TypRegion.create(id: 32, typ_country_id: 3, name:'烏來區')
  TypRegion.create(id: 33, typ_country_id: 3, name:'永和區')
  TypRegion.create(id: 34, typ_country_id: 3, name:'中和區')
  TypRegion.create(id: 35, typ_country_id: 3, name:'土城區')
  TypRegion.create(id: 36, typ_country_id: 3, name:'三峽區')
  TypRegion.create(id: 37, typ_country_id: 3, name:'樹林區')
  TypRegion.create(id: 38, typ_country_id: 3, name:'鶯歌區')
  TypRegion.create(id: 39, typ_country_id: 3, name:'三重區')
  TypRegion.create(id: 40, typ_country_id: 3, name:'新莊區')
  TypRegion.create(id: 41, typ_country_id: 3, name:'泰山區')
  TypRegion.create(id: 42, typ_country_id: 3, name:'林口區')
  TypRegion.create(id: 43, typ_country_id: 3, name:'蘆洲區')
  TypRegion.create(id: 44, typ_country_id: 3, name:'五股區')
  TypRegion.create(id: 45, typ_country_id: 3, name:'八里區')
  TypRegion.create(id: 46, typ_country_id: 3, name:'淡水區')
  TypRegion.create(id: 47, typ_country_id: 3, name:'三芝區')
  TypRegion.create(id: 48, typ_country_id: 3, name:'石門區')
  # Typ_regions 桃園市
  TypRegion.create(id: 49, typ_country_id: 4, name:'中壢區')
  TypRegion.create(id: 50, typ_country_id: 4, name:'平鎮區')
  TypRegion.create(id: 51, typ_country_id: 4, name:'龍潭區')
  TypRegion.create(id: 52, typ_country_id: 4, name:'楊梅區')
  TypRegion.create(id: 53, typ_country_id: 4, name:'新屋區')
  TypRegion.create(id: 54, typ_country_id: 4, name:'觀音區')
  TypRegion.create(id: 55, typ_country_id: 4, name:'桃園區')
  TypRegion.create(id: 56, typ_country_id: 4, name:'龜山區')
  TypRegion.create(id: 57, typ_country_id: 4, name:'八德區')
  TypRegion.create(id: 58, typ_country_id: 4, name:'大溪區')
  TypRegion.create(id: 59, typ_country_id: 4, name:'復興區')
  TypRegion.create(id: 60, typ_country_id: 4, name:'大園區')
  TypRegion.create(id: 61, typ_country_id: 4, name:'蘆竹區')
  # Typ_regions 新竹市
  TypRegion.create(id: 62, typ_country_id: 5, name:'東區')
  TypRegion.create(id: 63, typ_country_id: 5, name:'北區')
  TypRegion.create(id: 64, typ_country_id: 5, name:'香山區')
  # Typ_regions 新竹縣
  TypRegion.create(id: 65, typ_country_id: 6, name:'竹北市')
  TypRegion.create(id: 66, typ_country_id: 6, name:'湖口鄉')
  TypRegion.create(id: 67, typ_country_id: 6, name:'新豐鄉')
  TypRegion.create(id: 68, typ_country_id: 6, name:'新埔鎮')
  TypRegion.create(id: 69, typ_country_id: 6, name:'關西鎮')
  TypRegion.create(id: 70, typ_country_id: 6, name:'芎林鄉')
  TypRegion.create(id: 71, typ_country_id: 6, name:'寶山鄉')
  TypRegion.create(id: 72, typ_country_id: 6, name:'竹東鎮')
  TypRegion.create(id: 73, typ_country_id: 6, name:'五峰鄉')
  TypRegion.create(id: 74, typ_country_id: 6, name:'橫山鄉')
  TypRegion.create(id: 75, typ_country_id: 6, name:'尖石鄉')
  TypRegion.create(id: 76, typ_country_id: 6, name:'北埔鄉')
  TypRegion.create(id: 77, typ_country_id: 6, name:'峨眉鄉')
  # Typ_regions 苗栗縣
  TypRegion.create(id: 78, typ_country_id: 7, name:'竹南鎮')
  TypRegion.create(id: 79, typ_country_id: 7, name:'頭份鎮')
  TypRegion.create(id: 80, typ_country_id: 7, name:'三灣鄉')
  TypRegion.create(id: 81, typ_country_id: 7, name:'南庄鄉')
  TypRegion.create(id: 82, typ_country_id: 7, name:'獅潭鄉')
  TypRegion.create(id: 83, typ_country_id: 7, name:'後龍鎮')
  TypRegion.create(id: 84, typ_country_id: 7, name:'通霄鎮')
  TypRegion.create(id: 85, typ_country_id: 7, name:'苑裡鎮')
  TypRegion.create(id: 86, typ_country_id: 7, name:'苗栗市')
  TypRegion.create(id: 87, typ_country_id: 7, name:'造橋鄉')
  TypRegion.create(id: 88, typ_country_id: 7, name:'頭屋鄉')
  TypRegion.create(id: 89, typ_country_id: 7, name:'公館鄉')
  TypRegion.create(id: 90, typ_country_id: 7, name:'大湖鄉')
  TypRegion.create(id: 91, typ_country_id: 7, name:'泰安鄉')
  TypRegion.create(id: 92, typ_country_id: 7, name:'銅鑼鄉')
  TypRegion.create(id: 93, typ_country_id: 7, name:'三義鄉')
  TypRegion.create(id: 94, typ_country_id: 7, name:'西湖鄉')
  TypRegion.create(id: 95, typ_country_id: 7, name:'卓蘭鎮')
  # Typ_regions 台中市
  TypRegion.create(id: 96, typ_country_id: 8, name:'中區')
  TypRegion.create(id: 97, typ_country_id: 8, name:'東區')
  TypRegion.create(id: 98, typ_country_id: 8, name:'南區')
  TypRegion.create(id: 99, typ_country_id: 8, name:'西區')
  TypRegion.create(id: 100, typ_country_id: 8, name:'北區')
  TypRegion.create(id: 101, typ_country_id: 8, name:'北屯區')
  TypRegion.create(id: 102, typ_country_id: 8, name:'西屯區')
  TypRegion.create(id: 103, typ_country_id: 8, name:'南屯區')
  TypRegion.create(id: 104, typ_country_id: 8, name:'太平區')
  TypRegion.create(id: 105, typ_country_id: 8, name:'大里區')
  TypRegion.create(id: 106, typ_country_id: 8, name:'霧峰區')
  TypRegion.create(id: 107, typ_country_id: 8, name:'烏日區')
  TypRegion.create(id: 108, typ_country_id: 8, name:'豐原區')
  TypRegion.create(id: 109, typ_country_id: 8, name:'后里區')
  TypRegion.create(id: 110, typ_country_id: 8, name:'石岡區')
  TypRegion.create(id: 111, typ_country_id: 8, name:'東勢區')
  TypRegion.create(id: 112, typ_country_id: 8, name:'和平區')
  TypRegion.create(id: 113, typ_country_id: 8, name:'新社區')
  TypRegion.create(id: 114, typ_country_id: 8, name:'潭子區')
  TypRegion.create(id: 115, typ_country_id: 8, name:'大雅區')
  TypRegion.create(id: 116, typ_country_id: 8, name:'神岡區')
  TypRegion.create(id: 117, typ_country_id: 8, name:'大肚區')
  TypRegion.create(id: 118, typ_country_id: 8, name:'沙鹿區')
  TypRegion.create(id: 119, typ_country_id: 8, name:'龍井區')
  TypRegion.create(id: 120, typ_country_id: 8, name:'梧棲區')
  TypRegion.create(id: 121, typ_country_id: 8, name:'清水區')
  TypRegion.create(id: 122, typ_country_id: 8, name:'大甲區')
  TypRegion.create(id: 123, typ_country_id: 8, name:'外埔區')
  TypRegion.create(id: 124, typ_country_id: 8, name:'大安區')
  # Typ_regions 彰化縣
  TypRegion.create(id: 125, typ_country_id: 9, name:'彰化市')
  TypRegion.create(id: 126, typ_country_id: 9, name:'芬園鄉')
  TypRegion.create(id: 127, typ_country_id: 9, name:'花壇鄉')
  TypRegion.create(id: 128, typ_country_id: 9, name:'秀水鄉')
  TypRegion.create(id: 129, typ_country_id: 9, name:'鹿港鎮')
  TypRegion.create(id: 130, typ_country_id: 9, name:'福興鄉')
  TypRegion.create(id: 131, typ_country_id: 9, name:'線西鄉')
  TypRegion.create(id: 132, typ_country_id: 9, name:'和美鎮')
  TypRegion.create(id: 133, typ_country_id: 9, name:'伸港鄉')
  TypRegion.create(id: 134, typ_country_id: 9, name:'員林市')
  TypRegion.create(id: 135, typ_country_id: 9, name:'社頭鄉')
  TypRegion.create(id: 136, typ_country_id: 9, name:'永靖鄉')
  TypRegion.create(id: 137, typ_country_id: 9, name:'埔心鄉')
  TypRegion.create(id: 138, typ_country_id: 9, name:'溪湖鎮')
  TypRegion.create(id: 139, typ_country_id: 9, name:'大村鄉')
  TypRegion.create(id: 140, typ_country_id: 9, name:'埔鹽鄉')
  TypRegion.create(id: 141, typ_country_id: 9, name:'田中鎮')
  TypRegion.create(id: 142, typ_country_id: 9, name:'北斗鎮')
  TypRegion.create(id: 143, typ_country_id: 9, name:'田尾鄉')
  TypRegion.create(id: 144, typ_country_id: 9, name:'埤頭鄉')
  TypRegion.create(id: 145, typ_country_id: 9, name:'溪州鄉')
  TypRegion.create(id: 146, typ_country_id: 9, name:'竹塘鄉')
  TypRegion.create(id: 147, typ_country_id: 9, name:'二林鎮')
  TypRegion.create(id: 148, typ_country_id: 9, name:'大城鄉')
  TypRegion.create(id: 149, typ_country_id: 9, name:'芳苑鄉')
  TypRegion.create(id: 150, typ_country_id: 9, name:'二水鄉')
  # Typ_regions 南投縣
  TypRegion.create(id: 151, typ_country_id: 10, name:'南投市')
  TypRegion.create(id: 152, typ_country_id: 10, name:'中寮鄉')
  TypRegion.create(id: 153, typ_country_id: 10, name:'草屯鎮')
  TypRegion.create(id: 154, typ_country_id: 10, name:'國姓鄉')
  TypRegion.create(id: 155, typ_country_id: 10, name:'埔里鎮')
  TypRegion.create(id: 156, typ_country_id: 10, name:'仁愛鄉')
  TypRegion.create(id: 157, typ_country_id: 10, name:'名間鄉')
  TypRegion.create(id: 158, typ_country_id: 10, name:'集集鎮')
  TypRegion.create(id: 159, typ_country_id: 10, name:'水里鄉')
  TypRegion.create(id: 160, typ_country_id: 10, name:'魚池鄉')
  TypRegion.create(id: 161, typ_country_id: 10, name:'信義鄉')
  TypRegion.create(id: 162, typ_country_id: 10, name:'竹山鎮')
  TypRegion.create(id: 163, typ_country_id: 10, name:'鹿谷鄉')
  # Typ_regions 雲林縣
  TypRegion.create(id: 164, typ_country_id: 11, name:'斗南鎮')
  TypRegion.create(id: 165, typ_country_id: 11, name:'大埤鄉')
  TypRegion.create(id: 166, typ_country_id: 11, name:'虎尾鎮')
  TypRegion.create(id: 167, typ_country_id: 11, name:'土庫鎮')
  TypRegion.create(id: 168, typ_country_id: 11, name:'褒忠鄉')
  TypRegion.create(id: 169, typ_country_id: 11, name:'東勢鄉')
  TypRegion.create(id: 170, typ_country_id: 11, name:'台西鄉')
  TypRegion.create(id: 171, typ_country_id: 11, name:'崙背鄉')
  TypRegion.create(id: 172, typ_country_id: 11, name:'麥寮鄉')
  TypRegion.create(id: 173, typ_country_id: 11, name:'斗六市')
  TypRegion.create(id: 174, typ_country_id: 11, name:'林內鄉')
  TypRegion.create(id: 175, typ_country_id: 11, name:'古坑鄉')
  TypRegion.create(id: 176, typ_country_id: 11, name:'莿桐鄉')
  TypRegion.create(id: 177, typ_country_id: 11, name:'西螺鎮')
  TypRegion.create(id: 178, typ_country_id: 11, name:'二崙鄉')
  TypRegion.create(id: 179, typ_country_id: 11, name:'北港鎮')
  TypRegion.create(id: 180, typ_country_id: 11, name:'水林鄉')
  TypRegion.create(id: 181, typ_country_id: 11, name:'口湖鄉')
  TypRegion.create(id: 182, typ_country_id: 11, name:'四湖鄉')
  TypRegion.create(id: 183, typ_country_id: 11, name:'元長鄉')
  # Typ_regions 嘉義市
  TypRegion.create(id: 184, typ_country_id: 12, name:'東區')
  TypRegion.create(id: 185, typ_country_id: 12, name:'西區')
  # Typ_regions 嘉義縣
  TypRegion.create(id: 186, typ_country_id: 13, name:'番路鄉')
  TypRegion.create(id: 187, typ_country_id: 13, name:'梅山鄉')
  TypRegion.create(id: 188, typ_country_id: 13, name:'竹崎鄉')
  TypRegion.create(id: 189, typ_country_id: 13, name:'阿里山鄉')
  TypRegion.create(id: 190, typ_country_id: 13, name:'中埔鄉')
  TypRegion.create(id: 191, typ_country_id: 13, name:'大埔鄉')
  TypRegion.create(id: 192, typ_country_id: 13, name:'水上鄉')
  TypRegion.create(id: 193, typ_country_id: 13, name:'鹿草鄉')
  TypRegion.create(id: 194, typ_country_id: 13, name:'太保市')
  TypRegion.create(id: 195, typ_country_id: 13, name:'朴子市')
  TypRegion.create(id: 196, typ_country_id: 13, name:'東石鄉')
  TypRegion.create(id: 197, typ_country_id: 13, name:'六腳鄉')
  TypRegion.create(id: 198, typ_country_id: 13, name:'新港鄉')
  TypRegion.create(id: 199, typ_country_id: 13, name:'民雄鄉')
  TypRegion.create(id: 200, typ_country_id: 13, name:'大林鎮')
  TypRegion.create(id: 201, typ_country_id: 13, name:'溪口鄉')
  TypRegion.create(id: 202, typ_country_id: 13, name:'義竹鄉')
  TypRegion.create(id: 203, typ_country_id: 13, name:'布袋鎮')
  # Typ_regions 台南市
  TypRegion.create(id: 204, typ_country_id: 14, name:'中西區')
  TypRegion.create(id: 205, typ_country_id: 14, name:'東區')
  TypRegion.create(id: 206, typ_country_id: 14, name:'南區')
  TypRegion.create(id: 207, typ_country_id: 14, name:'北區')
  TypRegion.create(id: 208, typ_country_id: 14, name:'安平區')
  TypRegion.create(id: 209, typ_country_id: 14, name:'安南區')
  TypRegion.create(id: 210, typ_country_id: 14, name:'永康區')
  TypRegion.create(id: 211, typ_country_id: 14, name:'歸仁區')
  TypRegion.create(id: 212, typ_country_id: 14, name:'新化區')
  TypRegion.create(id: 213, typ_country_id: 14, name:'左鎮區')
  TypRegion.create(id: 214, typ_country_id: 14, name:'玉井區')
  TypRegion.create(id: 215, typ_country_id: 14, name:'楠西區')
  TypRegion.create(id: 216, typ_country_id: 14, name:'南化區')
  TypRegion.create(id: 217, typ_country_id: 14, name:'仁德區')
  TypRegion.create(id: 218, typ_country_id: 14, name:'關廟區')
  TypRegion.create(id: 219, typ_country_id: 14, name:'龍崎區')
  TypRegion.create(id: 220, typ_country_id: 14, name:'官田區')
  TypRegion.create(id: 221, typ_country_id: 14, name:'麻豆區')
  TypRegion.create(id: 222, typ_country_id: 14, name:'佳里區')
  TypRegion.create(id: 223, typ_country_id: 14, name:'西港區')
  TypRegion.create(id: 224, typ_country_id: 14, name:'七股區')
  TypRegion.create(id: 225, typ_country_id: 14, name:'將軍區')
  TypRegion.create(id: 226, typ_country_id: 14, name:'學甲區')
  TypRegion.create(id: 227, typ_country_id: 14, name:'北門區')
  TypRegion.create(id: 228, typ_country_id: 14, name:'新營區')
  TypRegion.create(id: 229, typ_country_id: 14, name:'後壁區')
  TypRegion.create(id: 230, typ_country_id: 14, name:'白河區')
  TypRegion.create(id: 231, typ_country_id: 14, name:'東山區')
  TypRegion.create(id: 232, typ_country_id: 14, name:'六甲區')
  TypRegion.create(id: 233, typ_country_id: 14, name:'下營區')
  TypRegion.create(id: 234, typ_country_id: 14, name:'柳營區')
  TypRegion.create(id: 235, typ_country_id: 14, name:'鹽水區')
  TypRegion.create(id: 236, typ_country_id: 14, name:'善化區')
  TypRegion.create(id: 237, typ_country_id: 14, name:'大內區')
  TypRegion.create(id: 238, typ_country_id: 14, name:'山上區')
  TypRegion.create(id: 239, typ_country_id: 14, name:'新市區')
  TypRegion.create(id: 240, typ_country_id: 14, name:'安定區')
  # Typ_regions 高雄市
  TypRegion.create(id: 241, typ_country_id: 15, name:'新興區')
  TypRegion.create(id: 242, typ_country_id: 15, name:'前金區')
  TypRegion.create(id: 243, typ_country_id: 15, name:'苓雅區')
  TypRegion.create(id: 244, typ_country_id: 15, name:'鹽埕區')
  TypRegion.create(id: 245, typ_country_id: 15, name:'鼓山區')
  TypRegion.create(id: 246, typ_country_id: 15, name:'旗津區')
  TypRegion.create(id: 247, typ_country_id: 15, name:'前鎮區')
  TypRegion.create(id: 248, typ_country_id: 15, name:'三民區')
  TypRegion.create(id: 249, typ_country_id: 15, name:'楠梓區')
  TypRegion.create(id: 250, typ_country_id: 15, name:'小港區')
  TypRegion.create(id: 251, typ_country_id: 15, name:'左營區')
  TypRegion.create(id: 252, typ_country_id: 15, name:'仁武區')
  TypRegion.create(id: 253, typ_country_id: 15, name:'大社區')
  TypRegion.create(id: 254, typ_country_id: 15, name:'南海島東沙群島')
  TypRegion.create(id: 255, typ_country_id: 15, name:'南海島南沙群島')
  TypRegion.create(id: 256, typ_country_id: 15, name:'岡山區')
  TypRegion.create(id: 257, typ_country_id: 15, name:'路竹區')
  TypRegion.create(id: 258, typ_country_id: 15, name:'阿蓮區')
  TypRegion.create(id: 259, typ_country_id: 15, name:'田寮區')
  TypRegion.create(id: 260, typ_country_id: 15, name:'燕巢區')
  TypRegion.create(id: 261, typ_country_id: 15, name:'橋頭區')
  TypRegion.create(id: 262, typ_country_id: 15, name:'梓官區')
  TypRegion.create(id: 263, typ_country_id: 15, name:'彌陀區')
  TypRegion.create(id: 264, typ_country_id: 15, name:'永安區')
  TypRegion.create(id: 265, typ_country_id: 15, name:'湖內區')
  TypRegion.create(id: 266, typ_country_id: 15, name:'鳳山區')
  TypRegion.create(id: 267, typ_country_id: 15, name:'大寮區')
  TypRegion.create(id: 268, typ_country_id: 15, name:'林園區')
  TypRegion.create(id: 269, typ_country_id: 15, name:'鳥松區')
  TypRegion.create(id: 270, typ_country_id: 15, name:'大樹區')
  TypRegion.create(id: 271, typ_country_id: 15, name:'旗山區')
  TypRegion.create(id: 272, typ_country_id: 15, name:'美濃區')
  TypRegion.create(id: 273, typ_country_id: 15, name:'六龜區')
  TypRegion.create(id: 274, typ_country_id: 15, name:'內門區')
  TypRegion.create(id: 275, typ_country_id: 15, name:'杉林區')
  TypRegion.create(id: 276, typ_country_id: 15, name:'甲仙區')
  TypRegion.create(id: 277, typ_country_id: 15, name:'桃源區')
  TypRegion.create(id: 278, typ_country_id: 15, name:'那瑪夏區')
  TypRegion.create(id: 279, typ_country_id: 15, name:'茂林區')
  TypRegion.create(id: 280, typ_country_id: 15, name:'茄萣區')
  # Typ_regions 屏東縣
  TypRegion.create(id: 281, typ_country_id: 16, name:'屏東市')
  TypRegion.create(id: 282, typ_country_id: 16, name:'三地門鄉')
  TypRegion.create(id: 283, typ_country_id: 16, name:'霧台鄉')
  TypRegion.create(id: 284, typ_country_id: 16, name:'瑪家鄉')
  TypRegion.create(id: 285, typ_country_id: 16, name:'九如鄉')
  TypRegion.create(id: 286, typ_country_id: 16, name:'里港鄉')
  TypRegion.create(id: 287, typ_country_id: 16, name:'高樹鄉')
  TypRegion.create(id: 288, typ_country_id: 16, name:'鹽埔鄉')
  TypRegion.create(id: 289, typ_country_id: 16, name:'長治鄉')
  TypRegion.create(id: 290, typ_country_id: 16, name:'麟洛鄉')
  TypRegion.create(id: 291, typ_country_id: 16, name:'竹田鄉')
  TypRegion.create(id: 292, typ_country_id: 16, name:'內埔鄉')
  TypRegion.create(id: 293, typ_country_id: 16, name:'萬丹鄉')
  TypRegion.create(id: 294, typ_country_id: 16, name:'潮州鎮')
  TypRegion.create(id: 295, typ_country_id: 16, name:'泰武鄉')
  TypRegion.create(id: 296, typ_country_id: 16, name:'來義鄉')
  TypRegion.create(id: 297, typ_country_id: 16, name:'萬巒鄉')
  TypRegion.create(id: 298, typ_country_id: 16, name:'崁頂鄉')
  TypRegion.create(id: 299, typ_country_id: 16, name:'新埤鄉')
  TypRegion.create(id: 300, typ_country_id: 16, name:'南州鄉')
  TypRegion.create(id: 301, typ_country_id: 16, name:'林邊鄉')
  TypRegion.create(id: 302, typ_country_id: 16, name:'東港鎮')
  TypRegion.create(id: 303, typ_country_id: 16, name:'琉球鄉')
  TypRegion.create(id: 304, typ_country_id: 16, name:'佳冬鄉')
  TypRegion.create(id: 305, typ_country_id: 16, name:'新園鄉')
  TypRegion.create(id: 306, typ_country_id: 16, name:'枋寮鄉')
  TypRegion.create(id: 307, typ_country_id: 16, name:'枋山鄉')
  TypRegion.create(id: 308, typ_country_id: 16, name:'春日鄉')
  TypRegion.create(id: 309, typ_country_id: 16, name:'獅子鄉')
  TypRegion.create(id: 310, typ_country_id: 16, name:'車城鄉')
  TypRegion.create(id: 311, typ_country_id: 16, name:'牡丹鄉')
  TypRegion.create(id: 312, typ_country_id: 16, name:'恆春鎮')
  TypRegion.create(id: 313, typ_country_id: 16, name:'滿州鄉')
  # Typ_regions 台東縣
  TypRegion.create(id: 314, typ_country_id: 17, name:'台東市')
  TypRegion.create(id: 315, typ_country_id: 17, name:'綠島鄉')
  TypRegion.create(id: 316, typ_country_id: 17, name:'蘭嶼鄉')
  TypRegion.create(id: 317, typ_country_id: 17, name:'延平鄉')
  TypRegion.create(id: 318, typ_country_id: 17, name:'卑南鄉')
  TypRegion.create(id: 319, typ_country_id: 17, name:'鹿野鄉')
  TypRegion.create(id: 320, typ_country_id: 17, name:'關山鎮')
  TypRegion.create(id: 321, typ_country_id: 17, name:'海端鄉')
  TypRegion.create(id: 322, typ_country_id: 17, name:'池上鄉')
  TypRegion.create(id: 323, typ_country_id: 17, name:'東河鄉')
  TypRegion.create(id: 324, typ_country_id: 17, name:'成功鎮')
  TypRegion.create(id: 325, typ_country_id: 17, name:'長濱鄉')
  TypRegion.create(id: 326, typ_country_id: 17, name:'太麻里鄉')
  TypRegion.create(id: 327, typ_country_id: 17, name:'金峰鄉')
  TypRegion.create(id: 328, typ_country_id: 17, name:'大武鄉')
  TypRegion.create(id: 329, typ_country_id: 17, name:'達仁鄉')
  # Typ_regions 花蓮縣
  TypRegion.create(id: 330, typ_country_id: 18, name:'花蓮市')
  TypRegion.create(id: 331, typ_country_id: 18, name:'新城鄉')
  TypRegion.create(id: 332, typ_country_id: 18, name:'秀林鄉')
  TypRegion.create(id: 333, typ_country_id: 18, name:'吉安鄉')
  TypRegion.create(id: 334, typ_country_id: 18, name:'壽豐鄉')
  TypRegion.create(id: 335, typ_country_id: 18, name:'鳳林鎮')
  TypRegion.create(id: 336, typ_country_id: 18, name:'光復鄉')
  TypRegion.create(id: 337, typ_country_id: 18, name:'豐濱鄉')
  TypRegion.create(id: 338, typ_country_id: 18, name:'瑞穗鄉')
  TypRegion.create(id: 339, typ_country_id: 18, name:'萬榮鄉')
  TypRegion.create(id: 340, typ_country_id: 18, name:'玉里鎮')
  TypRegion.create(id: 341, typ_country_id: 18, name:'卓溪鄉')
  TypRegion.create(id: 342, typ_country_id: 18, name:'富里鄉')
  # Typ_regions 宜蘭縣
  TypRegion.create(id: 343, typ_country_id: 19, name:'宜蘭市')
  TypRegion.create(id: 344, typ_country_id: 19, name:'頭城鎮')
  TypRegion.create(id: 345, typ_country_id: 19, name:'礁溪鄉')
  TypRegion.create(id: 346, typ_country_id: 19, name:'壯圍鄉')
  TypRegion.create(id: 347, typ_country_id: 19, name:'員山鄉')
  TypRegion.create(id: 348, typ_country_id: 19, name:'羅東鎮')
  TypRegion.create(id: 349, typ_country_id: 19, name:'三星鄉')
  TypRegion.create(id: 350, typ_country_id: 19, name:'大同鄉')
  TypRegion.create(id: 351, typ_country_id: 19, name:'五結鄉')
  TypRegion.create(id: 352, typ_country_id: 19, name:'冬山鄉')
  TypRegion.create(id: 353, typ_country_id: 19, name:'蘇澳鎮')
  TypRegion.create(id: 354, typ_country_id: 19, name:'南澳鄉')
  TypRegion.create(id: 355, typ_country_id: 19, name:'釣魚台')
  # Typ_regions 澎湖縣
  TypRegion.create(id: 356, typ_country_id: 20, name:'馬公市')
  TypRegion.create(id: 357, typ_country_id: 20, name:'西嶼鄉')
  TypRegion.create(id: 358, typ_country_id: 20, name:'望安鄉')
  TypRegion.create(id: 359, typ_country_id: 20, name:'七美鄉')
  TypRegion.create(id: 360, typ_country_id: 20, name:'白沙鄉')
  TypRegion.create(id: 361, typ_country_id: 20, name:'湖西鄉')
  # Typ_regions 金門縣
  TypRegion.create(id: 362, typ_country_id: 21, name:'金沙鎮')
  TypRegion.create(id: 363, typ_country_id: 21, name:'金湖鎮')
  TypRegion.create(id: 364, typ_country_id: 21, name:'金寧鄉')
  TypRegion.create(id: 365, typ_country_id: 21, name:'金城鎮')
  TypRegion.create(id: 366, typ_country_id: 21, name:'烈嶼鄉')
  TypRegion.create(id: 367, typ_country_id: 21, name:'烏坵鄉')
  # Typ_regions 連江縣
  TypRegion.create(id: 368, typ_country_id: 22, name:'南竿鄉')
  TypRegion.create(id: 369, typ_country_id: 22, name:'北竿鄉')
  TypRegion.create(id: 370, typ_country_id: 22, name:'莒光鄉')
  TypRegion.create(id: 371, typ_country_id: 22, name:'東引鄉')
  end
end